### ISSUE TITLE
"Error The configuration flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Wellynounet** [jaidenlabelle/tuya-vacuum-maps#1] opened 2024-11-20 12:30 UTC
Hello , ive got a issue when i try add this integration in my HA  

"Error The configuration flow could not be loaded: 500 Internal Server Error Server got itself in trouble

![image](https://github.com/user-attachments/assets/32e80d4b-4998-4849-a726-4aa094df0112)

**Comment by jaidenlabelle** [comment] 2024-11-20 21:43
Can you share the home assistant log file?

**Comment by Wellynounet** [comment] 2024-11-20 21:59
> Can you share the home assistant log file?

[2024-11-20 22:58:04.034 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package lz4: error: Failed to prepare distributions
  Caused by: Failed to download and build `lz4==4.3.3`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)

[stdout]
running bdist_wheel
running build
running build_py
creating build/lib.linux-x86_64-cpython-312/lz4
copying lz4/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4
copying lz4/version.py -> build/lib.linux-x86_64-cpython-312/lz4
creating build/lib.linux-x86_64-cpython-312/lz4/block
copying lz4/block/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/block
creating build/lib.linux-x86_64-cpython-312/lz4/frame
copying lz4/frame/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/frame
running build_ext
building 'lz4._version' extension
creating build/temp.linux-x86_64-cpython-312/lz4
creating build/temp.linux-x86_64-cpython-312/lz4libs
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Ilz4libs -I/tmp/.tmpTGwXfr/builds-v0/.tmpjlVyRc/include -I/usr/local/include/python3.12 -c lz4/_version.c -o build/temp.linux-x86_64-cpython-312/lz4/_version.o -O3 -Wall -Wundef

[stderr]
/tmp/.tmpTGwXfr/builds-v0/.tmpjlVyRc/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/tmp/.tmpTGwXfr/builds-v0/.tmpjlVyRc/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:92: UserWarning: version of lz4 already set
  warnings.warn(f"version of {dist_name} already set")
error: command 'gcc' failed: No such file or directory
2024-11-20 22:58:04.034 INFO (SyncWorker_4) [homeassistant.util.package] Attempting install of lz4
2024-11-20 22:58:05.655 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package lz4: error: Failed to prepare distributions
  Caused by: Failed to download and build `lz4==4.3.3`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)

[stdout]
running bdist_wheel
running build
running build_py
creating build/lib.linux-x86_64-cpython-312/lz4
copying lz4/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4
copying lz4/version.py -> build/lib.linux-x86_64-cpython-312/lz4
creating build/lib.linux-x86_64-cpython-312/lz4/block
copying lz4/block/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/block
creating build/lib.linux-x86_64-cpython-312/lz4/frame
copying lz4/frame/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/frame
running build_ext
building 'lz4._version' extension
creating build/temp.linux-x86_64-cpython-312/lz4
creating build/temp.linux-x86_64-cpython-312/lz4libs
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Ilz4libs -I/tmp/.tmpOy3Nts/builds-v0/.tmps7dt5s/include -I/usr/local/include/python3.12 -c lz4/_version.c -o build/temp.linux-x86_64-cpython-312/lz4/_version.o -O3 -Wall -Wundef

[stderr]
/tmp/.tmpOy3Nts/builds-v0/.tmps7dt5s/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/tmp/.tmpOy3Nts/builds-v0/.tmps7dt5s/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:92: UserWarning: version of lz4 already set
  warnings.warn(f"version of {dist_name} already set")
error: command 'gcc' failed: No such file or directory
2024-11-20 22:58:05.659 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1326, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1518, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3268, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3245, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 269, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 307, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for tuya_vacuum_maps not found: ['lz4'].](`url`)

**Comment by jaidenlabelle** [comment] 2024-11-20 23:27
After testing with a fresh install of home assistant, it seems like the issue is caused by another integration you installed using a different version of lz4 then the tuya-vacuum library does. I'll tweak the requirements of the library to work with different versions.

**Comment by jaidenlabelle** [comment] 2024-11-20 23:57
I released a new version, please let me know if it resolves the issue.

**Comment by Wellynounet** [comment] 2024-11-21 06:15
Hello a new issue pop up :)


https://github.com/user-attachments/assets/a8dbc969-9f23-44f2-9340-421d6a76691d



and i have delete my tuya integration to test and same with  or without

**Comment by williamwmd** [comment] 2024-11-21 15:20
> Olá, um novo problema apareceu :)
> 
>  tório_4zjMpbu5wG.mp4 
> e eu deletei minha integração tuya para testar e o mesmo com ou sem
> 
> ![imagem](https://private-user-images.githubusercontent.com/88185485/388379218-df4ca939-b4d7-479c-b716-bfb77b634fea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDI2MDcsIm5iZiI6MTczMjIwMjMwNywicGF0aCI6Ii84ODE4NTQ4NS8zODgzNzkyMTgtZGY0Y2E5MzktYjRkNy00NzljLWI3MTYtYmZiNzdiNjM0ZmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE1MTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNjI5MTE0ZWMzNDcyNTlhZTUxY2I0Yjk5MjcyOTkyMDRiZTM1MDMxNTU5OWE5NzBkZWQ1YjA3NzE3YTQ3MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i-khM57zw3LGF4raxNdg2CcFItIxdcj5UypXPZ63Oqg)

I'm getting the same error.
HA version: 2024.11.2

**Comment by jaidenlabelle** [comment] 2024-11-21 21:57
> Hello a new issue pop up :)
> thorium_4zjMpbu5wG.mp4
> 
> and i have delete my tuya integration to test and same with or without
> 
> ![image](https://private-user-images.githubusercontent.com/88185485/388379218-df4ca939-b4d7-479c-b716-bfb77b634fea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMjY0MjQsIm5iZiI6MTczMjIyNjEyNCwicGF0aCI6Ii84ODE4NTQ4NS8zODgzNzkyMTgtZGY0Y2E5MzktYjRkNy00NzljLWI3MTYtYmZiNzdiNjM0ZmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDIxNTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MDk2MzFlNjNiZDVhMmRiMTA1ZTU4ZjFmYzFmYTQwZWY5NThjNTNiNWQwOGQ2YjhhNmYzMzFiOGZjZDdkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9stoFC_YOFpOC4AmXVFPORSJsN8BrMB0G45_hwEAVpc)

Can you share your home assistant log again for both errors?

**Comment by jaidenlabelle** [comment] 2024-11-26 00:18
> Hello a new issue pop up :)
> thorium_4zjMpbu5wG.mp4
> 
> and i have delete my tuya integration to test and same with or without
> 
> ![image](https://private-user-images.githubusercontent.com/88185485/388379218-df4ca939-b4d7-479c-b716-bfb77b634fea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODA1NDksIm5iZiI6MTczMjU4MDI0OSwicGF0aCI6Ii84ODE4NTQ4NS8zODgzNzkyMTgtZGY0Y2E5MzktYjRkNy00NzljLWI3MTYtYmZiNzdiNjM0ZmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAwMTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMWRjY2RjZDdlZWFkNzIwYTVhYmZlNmU1YjQ2YWI1NTljMGJhZmEyMGNkNjY2NDMxZTZiOGQxYmU4MmNhMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y95Q1xf2sge7FCZ66yPWNzEFOdExZWwWOWc7Es3xsfI)

The invalid handler issue has been fixed in v0.1.2

**Comment by jaidenlabelle** [comment] 2024-11-26 00:31
> After testing with a fresh install of home assistant, it seems like the issue is caused by another integration you installed using a different version of lz4 then the tuya-vacuum library does. I'll tweak the requirements of the library to work with different versions.

After testing with v0.1.2, the issue with different lz4 versions seems to be solved

**Closed by jaidenlabelle** 2024-11-26 00:31 UTC
Labels: bug

**Comment by Wellynounet** [comment] 2024-11-26 20:08
eah everything work now: )

**Comment by jaidenlabelle** [comment] 2024-11-26 22:08
Thanks for letting me know, glad I was able to help you
